services:
  - type: web
    name: glow-flora-blog
    env: node
    buildCommand: cd glow-flora-blog-frontend && npm install && npm run build && cd ../glow-flora-blog-backend && npm install
    startCommand: cd glow-flora-blog-backend && npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
